### ISSUE TITLE
No Gtk.notebook in xapp

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/python-xapp#19]
I was working on default applications in linuxmint/cinnamon-control-center#273 when I found that there are no *add_gtk.notebook* function in the Xapp settings widgets module. Is it obsolete to use Gtk Notebook or is it not necessary in Xapps?

**Comment by mtwebster** [comment]
Hi,

We usually use a GtkStack when there's a situation where a notebook would be useful (SettingsStack in xapps). I suppose if there's a situation where it's just not practical to use one we could use a notebook, but since a stack is pretty flexible about how its controlled, it would be a rare situation.

**Comment by hsbasu** [comment]
@mtwebster Thanks for the clarification.
